大会・結果に関するテーブル定義の変更
progrunner17/honomara_web_env pull request #3
Opened 2020-05-01 07:24 UTC by hrsmrt

大会・結果に関するテーブル定義を変更しました。
最も大きな変更としては、日付をresultテーブルに移行しました。
記録の登録は簡単になり、大会管理も充実するはずです。

2020-05-01 07:31 UTC, hrsmrt commented
これに伴って、members_siteもresultページなどを書き換えています。

2020-05-01 10:31 UTC, progrunner17 commented
まず、変更をまとめると
1. フィールド名、テーブル名の変更
2. race_typeとraceをracesに統合と、それに伴う変更
  * 日付フィールドの移動
  * 獲得標高の
3. race_base(competitions)テーブルの主キーの変更と項目の追加



だと思います。

### 1 フィールド名、テーブル名の変更について
まず、フィールド名とテーブル名の変更についてだけど、
これは僕も面倒くさがって適当に決めたままにしてただけなので、他のコードと整合性が保たれるなら問題ないです👍（変更箇所が多いだろうけど）

もし変更する場合は、他の全てのテーブル名も合わせて、単数形か複数形かに統一してください。
（どっちがいいかは論争があるっぽいんだけど、特に僕にこだわりはないので好きにして大丈夫です）

### 2 race_typeとraceをracesに統合、およびそれに伴う変更について
これは難しい問題なんだけど、問題は以下の2つに集約されると思います。
* DBの設計として理論的に問題はないか？
* 使用用途にあっているか？

で、まずは理論的な側面について。（僕も独学でしかないから偉そうなことは言えないけれど）
まず、competition_idをresultsとraces両方が持つのは、無意味というか、チェックに余計に時間がかかったり、最悪その参照が壊れると、データベースが停止するかもしれないので、どちらか一方は削除すべきだとおもいます。（どっちを削除すべきかは後に）

あと、日付についてなんだけど、

どんなクエリを使うかっていう問題だと思います。
元の設計は、結果表示を大会別に表示するのと、レースの種別に検索するのに対応しやすくするためと、大会の日付を何度も入力させるのは面倒かなって思ったからです。

3. これも難しい問題なんだけど、まず最初に大会名を主キーにしていた理由としては、
1

2020-05-01 13:34 UTC, progrunner17 commented
本当は、大会記録周りは適当に設計したから、綺麗に設計しなおそうと思っていたのもあって、rejectしようと思ってたんだけど、せっかくたくさん実装してくれたみたいなので、重要なところだけ訂正してもらってマージすることにします👍

2020-05-01 13:46 UTC, sgotand requested changes
この他、テーブル名を複数形にするか単数形にするかは半分宗教戦争みたいなものらしいので僕はどちらでもいいんだけど、せめて全てのテーブルで統一しましょう〜（コードの修正量を考えると、単数に統一した方が良さそう）

2020-05-01 13:46 UTC, progrunner17 commented on scripts/create_tables_mysql.sql
> +  `competition_id`        INT         NOT NULL,  -- FOREIGN KEY REFERENCES competition_date(id)
racesにもcompetition_idがあって、いつか外部キー制約のチェックでDBが停止したり、最悪の場合データベースが壊れそうなので、こっちのcompetition_idは消してください。

2020-05-01 13:46 UTC, progrunner17 commented on scripts/migrate_data_to_mysql.py
> +    elif ('マラソン' in show_name) or ('キロ' in show_name) or ('マイル' in ['show_name']):
('マイル' in ['show_name']) は多分書き間違いだと思うので修正した方がいいと思います〜

2020-05-01 14:12 UTC, progrunner17 commented
それとも、僕に付き合ってDBの設計をもう少しに慎重に煮詰めてみる？笑

2020-05-01 14:20 UTC, hrsmrt commented
設計し直したいです！

2020-05-01 14:24 UTC, hrsmrt commented
分かりやすく、軽く、かつ充実したDB、サイトを目指したいです！

2020-05-02 06:30 UTC, progrunner17 commented
了解です。
まずは、このPRをrejectにしようと思った理由について。
いくつかあるけれど、第2正規形にすらなっていないというのも理由の一つです。

どこが問題か考えてみるといい勉強になると思います。

また、考えるときは、サロゲートキーを考えず、ナチュラルキー・複合キーで考えるといいと思います。

（難しそうだったらヒント出します）

2020-05-02 07:02 UTC, hrsmrt commented
* resultsテーブルにサロゲートキーを使う意味が無い
* resultsテーブルのcompetition_idは、race_idが定まれば一意に定まる→第2正規形でない
* racesテーブルは重複を含んでいる→第1正規形ですらない

2020-05-02 07:08 UTC, hrsmrt commented
種目は、フルやハーフなどだと、距離は定まっていて、制限時間も大体決まってる(累積標高もそこまで気にされない？)けど、トレイルやウルトラだと大会毎にそれぞれ異なる場合が多い
というところが難しい原因かなと感じてます。

2020-05-02 08:36 UTC, progrunner17 commented
そうだね👍（よく考えれば、competition_idの話はコメントでしてきしてたね）
ちなみに、racesテーブルは一応第1正規形ではあると思うよ（値としては重複を含める設計にしていないので)

ところで、制限時間はフルやハーフでも大会によって結構違う気がする。

...って感じで、DBの理論はある程度前提として気にすべきとは思うけど、結局問題なのは各属性の性質についてなんだよなぁ...

例えば僕としては、大会日程をメンバー毎に持たせるのはその性質的におかしい気がするんだよな...

2020-05-09 10:10 UTC, hrsmrt commented
とりあえず、感触を確かめるために、最有力案にしたがってテーブル定義を修正してみました。各ページの方も同様に修正しましたが、result、raceの登録フォームはまだです。


issue #5 での考察でまとまっていない部分に関しては、以下のようにしました。

* コース分類と結果の、距離と時間はカラムを分けた。
* コースの名前はcourseテーブルにのみ持たせた。
* 地形情報は、google map APIを利用したものには及ばないので保留。
* リレマラ 、駅伝に関しても保留。

2020-08-13 03:02 UTC, closed without merging